<?php
/**
 * @file DeletePlatform.sql
 *
 * @author Till Uhlig <till.uhlig@student.uni-halle.de>
 * @date 2014-2015
 */
?>

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `File`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP TRIGGER IF EXISTS `File_ADEL`;
DROP TRIGGER IF EXISTS `File_AINS`;
DROP PROCEDURE IF EXISTS `DBFileGetExistsPlatform`;
DROP PROCEDURE IF EXISTS `DBFileGetFile`;
DROP PROCEDURE IF EXISTS `DBFileGetFileByHash`;
DROP PROCEDURE IF EXISTS `DBFileGetFileByMimeType`;
DROP PROCEDURE IF EXISTS `DBFileGetAllFiles`;