SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `Setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Setting<?php echo $pre; ?>_<?php echo $object->getId(); ?>` (
  `SET_id` INT NOT NULL AUTO_INCREMENT,
  `SET_name` VARCHAR(255) NOT NULL,
  `SET_state` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SET_id`),
  UNIQUE INDEX `SET_id_UNIQUE` USING BTREE (`SET_id` ASC),
  UNIQUE INDEX `SET_name_UNIQUE` USING BTREE (`SET_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;