SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `Submission`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP TRIGGER IF EXISTS `Submission_BDEL`;
DROP TRIGGER IF EXISTS `Submission_BINS`;
DROP TRIGGER IF EXISTS `Submission_BUPD`;
DROP TRIGGER IF EXISTS `Submission_ADEL`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetExerciseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetExistsPlatform`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetGroupCourseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetGroupExerciseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetGroupSelectedCourseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetGroupSelectedExerciseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetGroupSelectedSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetGroupSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetSelectedCourseUserSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetSelectedExerciseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetSelectedSheetSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetSheetSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetSubmission`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetUserExerciseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetUserSheetSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetAllSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetCourseSubmissions`;
DROP PROCEDURE IF EXISTS `DBSubmissionGetCourseUserSubmissions`;