<?php
/**
 * @file DeletePlatform.sql
 *
 * @author Till Uhlig <till.uhlig@student.uni-halle.de>
 * @date 2014-2015
 */
?>

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `SelectedSubmission`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP TRIGGER IF EXISTS `SelectedSubmission_BINS`;
DROP TRIGGER IF EXISTS `SelectedSubmission_BUPD`;
DROP PROCEDURE IF EXISTS `DBSelectedSubmissionGetSheetSelected`;
DROP PROCEDURE IF EXISTS `DBSelectedSubmissionGetCourseSelected`;
DROP PROCEDURE IF EXISTS `DBSelectedSubmissionGetExerciseSelected`;
DROP PROCEDURE IF EXISTS `DBSelectedSubmissionGetExistsPlatform`;