#!/bin/bash
##########################################
# Aufruf des entsprechenden cx compilers #
#                                        #
# A.Th. 21.09.2007                       #
#########################################

### Analysieren der Parameter ###
if [ $# == 0 ] 
then
   echo "FEHLER: keine Eingabedatei" 1>&2;
   exit 412
fi

if [ $# -gt 1 ] 
then
  echo "FEHLER: nur eine Eingabedatei moeglich" 1>&2;
  exit 412
fi

### Dateinamen analysieren ###
endung=`echo $1 | cut -d. -f2`
compiler=$endung

if ([ "$endung" != "c0" ] && [ "$endung" != "c1" ] && [ "$endung" != "c2" ] && [ "$endung" != "c3" ] && [ "$endung" != "c4" ]);
then
   echo "FEHLER: Falsche Dateiendung" 1>&2;
   exit 412
fi

if [ ! -f $1 ]
then
   echo "FEHLER: Datei $1 existiert nicht" 1>&2;
   exit 404;
fi

### Ausführen des Compilers
akt_PATH=`pwd`;
#dat_o_end=`echo $1 | cut -d. -f1`
error=false;

cd `dirname $1`

if "${akt_PATH}/compiler/$compiler" "$1"
then
  find . -type f -iname "*.c" -print0 | while IFS= read -r -d $'\0' line; do
      s="$line";
      s=${s##*/};
      dat_o_end=${s%.*};
      if `gcc -o $dat_o_end $dat_o_end.c`
       then
          error=false;
       else
          error=true;
          exit $?;
          break;
       fi
  done
else
exit $?;
fi

cd $akt_PATH

##########################################
# Ende des Skriptes                      #
##########################################
