SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `Marking`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP TRIGGER IF EXISTS `Marking_BINS`;
DROP TRIGGER IF EXISTS `Marking_BUPD`;
DROP TRIGGER IF EXISTS `Marking_BDEL`;
DROP TRIGGER IF EXISTS `Marking_ADEL`;
DROP PROCEDURE IF EXISTS `DBMarkingGetExerciseMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetExistsPlatform`;
DROP PROCEDURE IF EXISTS `DBMarkingGetMarking`;
DROP PROCEDURE IF EXISTS `DBMarkingGetSheetMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetSubmissionMarking`;
DROP PROCEDURE IF EXISTS `DBMarkingGetTutorCourseMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetTutorExerciseMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetTutorSheetMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetUserGroupMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetAllMarkings`;
DROP PROCEDURE IF EXISTS `DBMarkingGetCourseMarkings`;