<?php

include_once dirname(__FILE__) . '/../../structures/DataObject.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-18 at 22:41:52.
 */
class DataObjectTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testDummy() {
        // dummy
    }

}
